# Generated by Django 3.2.6 on 2021-08-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turmas',
            new_name='Turma',
        ),
    ]
